name: "pre-release"

permissions:
  contents: write

on:
  push:
    branches:
      - "*"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install zip
        run: sudo apt-get install zip
      - name: Read Project Version
        id: read_version
        run: |
          version=$(grep -oP '<Version>\K[^<]+' ${GITHUB_REPOSITORY##*/}/${GITHUB_REPOSITORY##*/}.csproj)
          echo "::set-output name=project_version::$version"
      - name: "Build & test for Windows"
        run: |
          dotnet publish -c Release -r win-x64
          zip -j win.zip ${GITHUB_REPOSITORY##*/}/bin/Release/net8.0/win-x64/*
      - name: "Build & test for macOS"
        run: |
          dotnet publish -c Release -r osx-x64
          zip -j macos.zip ${GITHUB_REPOSITORY##*/}/bin/Release/net8.0/osx-x64/*
      - name: "Build & test for Linux"
        run: |
          dotnet publish -c Release -r linux-x64
          zip -j linux.zip ${GITHUB_REPOSITORY##*/}/bin/Release/net8.0/linux-x64/*
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          make_latest: true
          tag_name: "v${{ steps.read_version.outputs.project_version }}"
          files: |
            LICENSE.txt
            win.zip
            linux.zip
            macos.zip
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest